<a href="https://colab.research.google.com/github/RogerHeederer/DL_Entry_Pytorch/blob/master/PretrainedWordEmbedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ref: wikidocs Pytorch로 시작하는 딥러닝 입문

In [1]:
from torchtext import data, datasets

In [2]:
TEXT = data.Field(sequential=True, batch_first=True, lower=True)
LABEL = data.Field(sequential=False, batch_first = True)

In [3]:
trainset, testset = datasets.IMDB.splits(TEXT, LABEL)

downloading aclImdb_v1.tar.gz


aclImdb_v1.tar.gz: 100%|██████████| 84.1M/84.1M [00:10<00:00, 7.98MB/s]


In [4]:
len(trainset), len(testset)

(25000, 25000)

In [5]:
trainset[0]

In [6]:
print(vars(trainset[0]))

{'text': ['just', 're-saw', 'this', 'movie', 'after', 'thirty', 'seven', 'years.', 'i', 'was', 'eleven', 'years', 'old', 'and', 'caught', 'this', 'flick', 'on', 'south', 'beach', 'at', 'the', 'long', 'gone', 'cinema', 'theater', 'on', 'washington', 'avenue.', 'in', '1969,', 'i', 'thought', 'where', "it's", 'at!', 'was', 'a', 'very', 'good', 'movie.', 'now,', 'however,', 'after', 'almost', 'forty', 'years,', "it's", 'not', 'as', 'good', 'as', 'it', 'was.', 'times', 'have', 'changed,', 'and', 'this', 'movie', 'is', 'now', 'a', 'tired', 'old', 're-hash', 'of', 'the', 'war', 'between', 'the', 'generations.', 'it', 'did', 'however,', 'catch', 'a', 'place', 'in', 'time', 'which', 'is', 'just', 'a', 'memory.', "it's", 'really', 'interesting', 'to', 'see', 'the', 'mod', 'fashions,', 'the', 'old', 'vegas,', 'a', 'slim', 'don', 'rickles,', 'chain', 'smoking,', 'and', 'a', 'hip', 'opening', 'song.', 'the', 'acting', 'was', 'decent,', 'the', 'script', 'somewhat', 'out-dated,', 'but', 'the', 'memor

In [7]:
import torch
import torch.nn as nn
from torchtext.vocab import Vectors

앞서 MakeWord2Vec에서 훈련시킨 워드 임베딩 파일을 업로드 후 불러오기

즉 사전 훈련된 워드투백을 초기 임베딩으로 사용하는 것

In [13]:
from google.colab import drive
drive.mount('/content/drive')
# import sys
# sys.path.append('/content/drive/My Drive/RogerHeederer/DL_entry_PyTorch/')

Mounted at /content/drive


In [32]:
vectors = Vectors(name = "/content/drive/My Drive/RogerHeederer/DL_entry_PyTorch/eng_w2v")

In [33]:
#단어 집합을 만듬과 동시에 임베딩 벡터값들 초기화
TEXT.build_vocab(trainset, vectors=vectors, max_size=10000, min_freq=10)
#max_size : 단어 집합 크기 제한
#min_freq : 최소 등장 빈도수 이상만 허용
#vectors = vectors : trainset에서 만들어진 단어 집합의 단어들을. env_w2v에 저장되어 있던 임베딩 벡터값으로 초기화

In [34]:
TEXT.vocab.stoi['the'],TEXT.vocab.stoi['seeing']

(2, 296)

In [35]:
len(TEXT.vocab) # 10000개의 단어 + <unk> + <pad>

10002

In [36]:
print('임베딩 벡터의 개수와 차원 : {}'.format(TEXT.vocab.vectors.shape))

임베딩 벡터의 개수와 차원 : torch.Size([10002, 100])


In [37]:
# 임베딩 벡터는 단어의 개수와 마찬가지로 10002개를 가지며, 100차원을 가짐
print(TEXT.vocab.vectors[0]) #<unk>의 임베딩 벡터값
print(TEXT.vocab.vectors[1]) #<pad>의 임베딩 벡터값
print(TEXT.vocab.vectors[296]) # 'seeing' 단어의 임베딩 벡터값

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])
tensor([ 2.0410e-01, -1.0951e+00,  8.3372e-01, -4.1061e-01,  9.4602e-01,
        -7.6238e-01, -1.2041e+00, -1.5873e+00

In [38]:
TEXT.vocab.stoi['self-indulgent']

10000

In [39]:
#기존에 없었던 단어인 self-indulgent의 임베딩 값 확인해보자, 0으로 초기화 되어 있네.
TEXT.vocab.vectors[10000]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [40]:
#위에 만들어진 임베딩 벡터들을 nn.Embedding()의 초기 값으로 사용해보자
embedding_layer = nn.Embedding.from_pretrained(TEXT.vocab.vectors, freeze=False)

In [41]:
print(embedding_layer(torch.LongTensor([296])))

tensor([[ 2.0410e-01, -1.0951e+00,  8.3372e-01, -4.1061e-01,  9.4602e-01,
         -7.6238e-01, -1.2041e+00, -1.5873e+00, -7.7787e-01, -1.6994e-01,
         -3.6630e-01,  8.7523e-01,  4.7680e-01,  1.0039e+00, -1.1515e+00,
         -3.7671e-02,  3.7903e-01, -1.2890e-03,  7.4898e-01, -5.5448e-01,
         -4.0147e-01,  5.9673e-01, -2.1892e+00,  1.6189e+00, -1.6594e+00,
          8.1712e-01,  2.3500e-01,  3.3066e-01,  1.1302e+00,  1.5283e+00,
          8.4723e-01, -1.1840e+00,  1.0490e+00, -9.4660e-01,  1.1751e+00,
         -2.9518e-01, -1.2644e+00,  1.3162e-01, -9.1135e-01, -6.5728e-01,
          9.2925e-01,  5.2573e-01,  1.8125e+00,  1.3335e+00,  5.5324e-01,
          1.4577e-01,  6.4391e-01,  1.7944e-01, -1.4886e+00, -2.3775e+00,
         -2.4572e-01, -1.1472e+00,  4.5241e-01, -9.2046e-01,  2.3898e-01,
         -7.6667e-01, -1.0596e+00,  1.7414e+00, -1.3937e+00,  1.3663e+00,
          6.3256e-01, -4.6279e-01, -7.7839e-01, -4.7372e-01, -7.4891e-01,
         -8.8902e-01,  1.2788e+00, -8.

#토치텍스트에서 제공하는 사전 훈련된 워드 임베딩

In [43]:
from torchtext.vocab import GloVe

In [46]:
TEXT.build_vocab(trainset, vectors=GloVe(name='6B', dim=300), max_size=10000, min_freq=10)
LABEL.build_vocab(trainset)

In [48]:
print('글로브 임베딩 벡터의 개수와 차원: {}'.format(TEXT.vocab.vectors.shape))

글로브 임베딩 벡터의 개수와 차원: torch.Size([10002, 300])


In [49]:
print(TEXT.vocab.vectors[296]) #seeing의 백터값

tensor([ 7.3362e-03,  1.5647e-01,  1.3821e-01, -1.8967e-01, -1.6663e-01,
         8.5072e-02, -7.0639e-02,  3.2704e-02,  2.6037e-02, -1.2017e+00,
         1.6040e-01, -1.5037e-01,  6.3969e-02,  2.8800e-02, -1.9354e-01,
        -1.5935e-01,  1.6052e-01, -3.7750e-01,  1.3926e-02,  3.1030e-02,
         3.7556e-02,  3.2161e-01,  2.9999e-01,  8.8554e-02,  2.0330e-01,
        -1.3384e-01,  1.5226e-01, -6.4890e-01,  2.4216e-01,  5.6653e-02,
        -1.8582e-01, -4.7473e-02, -4.7652e-01, -4.1552e-01, -1.2617e+00,
         2.8657e-01, -6.7495e-01, -3.5803e-02,  1.9523e-01,  1.5448e-01,
         1.0258e-01, -4.7372e-01,  1.0709e-01, -1.6940e-01,  1.2095e-01,
        -2.8649e-01,  3.4973e-01,  3.3700e-01,  1.2891e-01, -2.4193e-01,
         2.0085e-01, -3.1765e-01,  7.3575e-02,  1.3195e-01, -1.9057e-01,
         2.4340e-01,  1.4757e-01,  1.0710e-02,  2.4529e-01,  1.9576e-01,
         1.4003e-02, -1.9702e-01,  2.9533e-01,  4.5405e-01, -3.6360e-03,
        -1.0963e-01, -1.3476e-01, -3.8186e-01,  2.9

In [53]:
TEXT.vocab.stoi['self-indulgent']

10000

In [55]:
print(TEXT.vocab.vectors[10000])

tensor([ 7.7240e-01, -1.8002e-01,  2.0717e-01,  6.4022e-01,  1.1135e-01,
        -2.7689e-01,  1.7558e-01,  2.8250e-02,  3.1618e-01,  9.6400e-01,
         1.4508e-01, -5.0661e-02, -4.8165e-01,  1.4246e-02,  4.8416e-01,
        -3.9707e-01, -1.4038e-01, -1.4026e-02,  3.9789e-01, -3.7785e-01,
        -3.2327e-01,  2.2370e-01, -8.9342e-01,  8.2437e-02,  4.1199e-01,
        -1.1075e-01, -6.5089e-03, -6.2119e-04, -6.4469e-03,  7.8493e-02,
         5.9040e-02,  3.7689e-01,  9.5742e-02, -2.1513e-01,  1.1376e+00,
         4.8430e-01, -4.6451e-01, -1.0646e-02, -7.7405e-02,  2.0980e-01,
         3.5975e-02,  3.9363e-01,  6.5145e-02, -8.3382e-01,  1.7214e-01,
         5.8430e-01, -1.6715e-01, -3.4118e-01, -3.8457e-02, -5.3392e-01,
         6.2248e-02, -3.9097e-02,  3.6754e-01, -1.7611e-01, -2.3654e-01,
         1.1631e-01, -6.1311e-02, -1.0939e-01,  3.6544e-01,  3.6586e-01,
         8.3805e-02,  1.1935e-01, -1.3947e-01,  2.5586e-01,  2.2673e-01,
         4.2010e-01, -5.5817e-02, -4.8520e-01,  2.8

In [57]:
embedding_layer = nn.Embedding.from_pretrained(TEXT.vocab.vectors, freeze=False)

In [58]:
embedding_layer(torch.LongTensor([10000]))

tensor([[ 7.7240e-01, -1.8002e-01,  2.0717e-01,  6.4022e-01,  1.1135e-01,
         -2.7689e-01,  1.7558e-01,  2.8250e-02,  3.1618e-01,  9.6400e-01,
          1.4508e-01, -5.0661e-02, -4.8165e-01,  1.4246e-02,  4.8416e-01,
         -3.9707e-01, -1.4038e-01, -1.4026e-02,  3.9789e-01, -3.7785e-01,
         -3.2327e-01,  2.2370e-01, -8.9342e-01,  8.2437e-02,  4.1199e-01,
         -1.1075e-01, -6.5089e-03, -6.2119e-04, -6.4469e-03,  7.8493e-02,
          5.9040e-02,  3.7689e-01,  9.5742e-02, -2.1513e-01,  1.1376e+00,
          4.8430e-01, -4.6451e-01, -1.0646e-02, -7.7405e-02,  2.0980e-01,
          3.5975e-02,  3.9363e-01,  6.5145e-02, -8.3382e-01,  1.7214e-01,
          5.8430e-01, -1.6715e-01, -3.4118e-01, -3.8457e-02, -5.3392e-01,
          6.2248e-02, -3.9097e-02,  3.6754e-01, -1.7611e-01, -2.3654e-01,
          1.1631e-01, -6.1311e-02, -1.0939e-01,  3.6544e-01,  3.6586e-01,
          8.3805e-02,  1.1935e-01, -1.3947e-01,  2.5586e-01,  2.2673e-01,
          4.2010e-01, -5.5817e-02, -4.