<a href="https://colab.research.google.com/github/RogerHeederer/DL_Entry_Pytorch/blob/master/SoftmaxRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ref : wikidocs 파이토치로 시작하는 딥러닝 입문

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

x_train은 샘플 8개. 각 샘플은 4개의 특성(features)를 가지고 있음

y_train은 0,1,2. 3개의 클래스가 존재

In [3]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [4]:
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [5]:
y_one_hot = torch.zeros(8,3)
y_one_hot

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])

In [7]:
print(y_one_hot.shape)

torch.Size([8, 3])


In [8]:
# 가중치 행렬의 크기는 4 X 3이 되어야 한다.
W = torch.zeros((4,3), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
optimizer = optim.SGD([W, b], lr=0.1) #경사하강법을 옵티마이져로 사용

In [11]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  
  hypothesis = F.softmax(x_train.matmul(W) + b, dim=1)
  cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
        ))


Epoch    0/1000 Cost: 0.985576
Epoch  100/1000 Cost: 0.759040
Epoch  200/1000 Cost: 0.688919
Epoch  300/1000 Cost: 0.642395
Epoch  400/1000 Cost: 0.603376
Epoch  500/1000 Cost: 0.567557
Epoch  600/1000 Cost: 0.533244
Epoch  700/1000 Cost: 0.499622
Epoch  800/1000 Cost: 0.466241
Epoch  900/1000 Cost: 0.432838
Epoch 1000/1000 Cost: 0.399290


소프트맥스 회귀 구현 (하이-레벨단)

In [12]:
# 가중치 행렬의 크기는 4 X 3이 되어야 한다.
W = torch.zeros((4,3), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
optimizer = optim.SGD([W, b], lr=0.1) #경사하강법을 옵티마이져로 사용

In [13]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  z = x_train.matmul(W) + b
  cost = F.cross_entropy(z, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))


Epoch    0/1000 Cost: 1.098612
Epoch  100/1000 Cost: 0.761050
Epoch  200/1000 Cost: 0.689991
Epoch  300/1000 Cost: 0.643229
Epoch  400/1000 Cost: 0.604117
Epoch  500/1000 Cost: 0.568255
Epoch  600/1000 Cost: 0.533922
Epoch  700/1000 Cost: 0.500291
Epoch  800/1000 Cost: 0.466908
Epoch  900/1000 Cost: 0.433506
Epoch 1000/1000 Cost: 0.399962


In [14]:
W

tensor([[-3.6761, -0.1014,  3.7776],
        [-0.6601, -0.4641,  1.1242],
        [ 2.3178, -0.4808, -1.8370],
        [-0.6030,  1.4281, -0.8252]], requires_grad=True)

In [15]:
b

tensor([7.0816e-08], requires_grad=True)