<a href="https://colab.research.google.com/github/RogerHeederer/DL_Entry_Pytorch/blob/master/TensorManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reference :https://wikidocs.net/
Pytorch로 시작하는 딥 러닝 입문

In [55]:
!git clone https://github.com/RogerHeederer/DL_entry_PyTorch.git

fatal: destination path 'DL_entry_PyTorch' already exists and is not an empty directory.


In [ ]:
import torch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim())

1


In [ ]:
print(t.shape)

torch.Size([7])


In [ ]:
print(t.size())

torch.Size([7])


In [ ]:
print(t[0], t[1], t[-1])

tensor(0.) tensor(1.) tensor(6.)


In [ ]:
print(t[2:5], t[4:-1])

tensor([2., 3., 4.]) tensor([4., 5.])


In [ ]:
print(t[:2], t[3:])

tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D with pytorch

In [ ]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [ ]:
print(t[:, :-1]) # 첫번째 차원은 모두 선택, 두번째 차원에서는 맨 마지막꺼 빼고 다 가져오기

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


##브로드캐스팅

In [ ]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [ ]:
# vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
# 2x1 Vector + 1 x 2 vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
print(m1.shape)
print(m2.shape)

torch.Size([1, 2])
torch.Size([2, 1])


##행렬곱셈과 곱셈의 차이

In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('shape of matrix 1: ', m1.shape)
print('shape of matrix 2: ', m2.shape)
print(m1.matmul(m2))

shape of matrix 1:  torch.Size([2, 2])
shape of matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
# 엘리먼트 와이즈 곱셈 = 그냥 곱셈
print(m1 * m2) # 2 X 2로 브로드 캐스팅 된다
print(m1.mul(m2))  # matmul과 다르다

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## 평균구하기

In [ ]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())

tensor(2.5000)


In [ ]:
a = t.mean(dim=0)
print(a, a.shape) #dim = 0은 첫번째 차원 의미/ #행렬에서 첫번째 차원은 행을 의미

# 인자로 dim을 주면 해당 차원을 제거한다는 의미. 즉 dim = 0을 인자로 주면 첫번째 차원(행)을 제거한다는 말
# 다시 말하면 column만 남긴다는 의미. 

# 2x2 -> 1x2

tensor([2., 3.]) torch.Size([2])


In [ ]:
b = t.mean(dim=1)
print(b, b.shape) # 이번에는 dim = 1을 주겠다. 두번째 차원(Column)을 제거하겠다는 의미

# 2x2 -> 2x1

tensor([1.5000, 3.5000]) torch.Size([2])


In [ ]:
print(t.mean(dim=-1)) # 마지막 차원을 제거한다 = 결국 열의 차원을 제거한다는 소리


tensor([1.5000, 3.5000])


##덧셈하기

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.sum())
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1))# 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max와 argMax

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max())

tensor(4.)


In [ ]:
print(t.max(dim=0)) #행을 제거함/ dim을 인자로 주면 argmax까지 같이 계산해서 던져줌

# [[1, 2]
#  [3, 4]]
# 첫번째 열에서 0번 인덱스는 1, 1번 인덱스는 3
# 두번째 열에서 0번 인덱스는 2, 1번 인덱스는 4
# 3과 4가 리턴되었으니 argmax 값은 1번 인덱스,  1번 인덱스

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [ ]:
# max값 armmax값 따로 리턴 받기
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [ ]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
